### ISSUE TITLE
Broken support for lambdas

### ISSUE THREAD

**Issue by terlar** [nickmccurdy/add-hooks#6]
It seems you cannot bind a lambda when using `add-hooks-pair`, am I doing something wrong or is it something that should be supported?

```
(add-hooks-pair '(emacs-startup minibuffer-setup)
                #'(lambda ()
                   (set-window-fringes (minibuffer-window) 0 0 nil)))
```

This is an example of code that doesn't work.

**Comment by nickserv** [comment]
This is not supported right now. Leaving this out was kind of intentional because I personally don't think lambda hooks are good practice (since you can't refer to them by symbol to remove, inspect, or customize them). I would recommend changing your inline lambda to a `defun` and referencing its symbol in `add-hooks-pair`.

```emacs
(defun my-window-fringes () (set-window-fringes (minibuffer-window) 0 0 nil)))
(add-hooks-pair '(emacs-startup minibuffer-setup) 'my-window-fringes)
```

 If you'd prefer inline lambdas, I'd be happy to add them if we can retain back compatibility.

**Comment by terlar** [comment]
Your reasoning makes sense and I suspected it was something like that. Just sometimes when I add hooks to modes like `(linum-mode -1)` it feels a bit cumbersome to have to define a function first to do that kind of operation. You define functions for those kind of things also? Perhaps add `disable-linum-mode` style functions for all those kind of things that I want to toggle off?

**Comment by nickserv** [comment]
My current approach is to define functions for all hooks. However I haven't used mode disabling hooks like that, and I see how that could be cumbersome (and hard to read). It seems like adding lamba support is a good idea at least for cases like this (and to ease migration of users that aren't used to creating hook functions).

I'm debugging some unit tests to figure out why lambdas aren't working, I'll try to have a pull request  with a simple implementation up soon.

**Comment by nickmccurdy** [comment]
See #7.

**Comment by nickserv** [comment]
This should be fixed (once the MELPA package gets updated), let me know how it works for you
